[package]
name = "data-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.35"
color-eyre = "0.6.3"
csv = "1.3.1"
eyre = "0.6.12"
serde = "1.0.219"
sqlx = "0.8.3"
sqlx-cli = "0.8.3"
